#!/usr/bin/env bash
read -p "Enter commit mensage: " mensage
echo "Commit mensage: $mensage"
git init
git add --all
git commit -m "$mensage"
git remote add origin https://github.com/guilhermerodriguesti/osweb.git
git push -u origin master